apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    app: init-app
spec:
  containers:
  - name: nginix
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: workdir
  initContainers:
  - name: init-cont
    image: busybox
    command: ["/bin/sh"]
    args: ["-c","echo '<html><hl>This is init container <hl><html>' >> /work-dir/index.html"]
    volumeMounts:
    - mountPath: "/work-dir"
      name: workdir
  volumes:
  - name: workdir
    emptyDir: {}
