apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container
  labels:
    app: sidecar-app
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
     - mountPath: "/var/log/nginx"
       name: logs-volume
   
  - name: side-car
    image: busybox
    command: ["/bin/sh"]
    args: ["-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 5; done"]
    volumeMounts:
    - mountPath: "/var/log/nginx"
      name: logs-volume
  
  volumes:
   - name: logs-volume
     emptyDir: {}
