apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-first-daemonset
spec:
  selector:
    matchLabels:
      app: nginx-daemonset-template
  template:
    metadata:
      labels:
        app: nginx-daemonset-template
    spec:
      containers:
      - name: nginx-da
        image: nginx
        ports:
        - containerPort: 80
