apiVersion: v1
kind: Service
metadata:
  name: headless-np-service
spec:
  clusterIP: None
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - name: http
    nodePort: 30095
    port: 8087
    targetPort: 80
