apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-taint-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx 
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      tolerations:
      - key: environment
        value: test
        effect: NoSchedule
        operator: Equal
      containers:
      - name: nginx-dp
        image: nginx:1.14.2
        ports:
        - containerPort: 80
