apiVersion: v1
kind: Service
metadata:
  name: ip-svc
  namespace: ip-app-ns
spec:
  type: NodePort
  selector:
    app: ip-app
  ports:
  - name: http
    nodePort: 30090
    port: 8090
    targetPort: 80
