apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
  namespace: ip-app-ns
  labels:
    app: ip-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ipapp
        image: rajath177/ip-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
