apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  containers:
  - name: nginx-p
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-config-1
          key: environment
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: my-config-1
          key: db_url
