apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "This is first job"]
      restartPolicy: Never
