apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    volume: test
spec:
  storageClassName: local
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/ubuntu/pv/vol"
